import type { Product, Project, Document, UserSettings } from '../types'

export const SAMPLE_SETTINGS: UserSettings = {
  displayName: '山田 花子',
  email: 'hanako@example.com',
  companyName: 'Lumière Atelier',
  companyAddress: '東京都渋谷区神南1-2-3 クリエイタービル4F',
  companyPhone: '03-1234-5678',
  logoUrl: '',
  taxRate: 10,
  defaultCurrency: 'JPY',
  defaultPaymentTerms: '納品後30日以内',
  outputIncludeLogo: true,
  outputIncludeTax: true,
  outputFormat: 'a4',
}

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    name: 'Lumière Candle Line',
    businessType: 'product',
    salesChannels: ['ec', 'store', 'wholesale'],
    userRole: 'owner',
    selectedCostItems: ['material', 'packaging', 'shipping', 'payment_fee', 'rent', 'labor'],
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-03-15T14:30:00Z',
  },
  {
    id: 'proj-002',
    name: '春夏コレクション 2026',
    businessType: 'product',
    salesChannels: ['ec', 'made_to_order'],
    userRole: 'owner',
    selectedCostItems: ['material', 'processing', 'packaging', 'shipping', 'ec_fee', 'payment_fee'],
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-04-01T11:00:00Z',
  },
]

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    projectId: 'proj-001',
    name: 'アロマキャンドル ラベンダー S',
    code: 'ARC-LAV-S',
    category: 'home',
    colors: ['パープル', 'ホワイト'],
    sizes: ['S (50g)'],
    variants: [
      { id: 'v-001-1', color: 'パープル', size: 'S (50g)', sku: 'ARC-LAV-S-PU', stock: 24 },
      { id: 'v-001-2', color: 'ホワイト', size: 'S (50g)', sku: 'ARC-LAV-S-WH', stock: 18 },
    ],
    sellingPrice: 2200,
    wholesalePrice: 1100,
    unitCost: 480,
    additionalCosts: [],
    monthlyFixedCost: 60000,
    paymentFeeRate: 3.6,
    discountRate: 0,
    shippingCost: 600,
    salesChannels: ['ec', 'store'],
    status: 'active',
    expectedSalesVolume: 30,
    memo: '定番人気No.1。リピーター率が高い。',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'prod-002',
    projectId: 'proj-001',
    name: 'アロマキャンドル シトラス L',
    code: 'ARC-CIT-L',
    category: 'home',
    colors: ['イエロー', 'オレンジ'],
    sizes: ['L (150g)'],
    variants: [
      { id: 'v-002-1', color: 'イエロー', size: 'L (150g)', sku: 'ARC-CIT-L-YL', stock: 12 },
      { id: 'v-002-2', color: 'オレンジ', size: 'L (150g)', sku: 'ARC-CIT-L-OR', stock: 8 },
    ],
    sellingPrice: 3800,
    wholesalePrice: 1900,
    unitCost: 950,
    additionalCosts: [],
    monthlyFixedCost: 60000,
    paymentFeeRate: 3.6,
    discountRate: 0,
    shippingCost: 800,
    salesChannels: ['ec', 'store', 'wholesale'],
    status: 'active',
    expectedSalesVolume: 20,
    memo: 'ギフト向け。包装オプション検討中。',
    createdAt: '2026-01-20T09:00:00Z',
    updatedAt: '2026-04-05T10:00:00Z',
  },
  {
    id: 'prod-003',
    projectId: 'proj-001',
    name: 'リードディフューザー ローズ',
    code: 'RDF-ROS',
    category: 'home',
    colors: ['ピンク', 'クリア'],
    sizes: ['100ml', '200ml'],
    variants: [
      { id: 'v-003-1', color: 'ピンク', size: '100ml', sku: 'RDF-ROS-PK-100', stock: 15 },
      { id: 'v-003-2', color: 'クリア', size: '200ml', sku: 'RDF-ROS-CL-200', stock: 10 },
    ],
    sellingPrice: 4500,
    wholesalePrice: 2250,
    unitCost: 1200,
    additionalCosts: [],
    monthlyFixedCost: 60000,
    paymentFeeRate: 3.6,
    discountRate: 20,
    shippingCost: 800,
    salesChannels: ['wholesale'],
    status: 'active',
    expectedSalesVolume: 10,
    memo: '卸先向け。20%割引適用済み。',
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'prod-004',
    projectId: 'proj-001',
    name: 'ルームスプレー ハーブ',
    code: 'RSP-HRB',
    category: 'home',
    colors: ['グリーン'],
    sizes: ['50ml'],
    variants: [
      { id: 'v-004-1', color: 'グリーン', size: '50ml', sku: 'RSP-HRB-GR-50', stock: 0 },
    ],
    sellingPrice: 1800,
    wholesalePrice: 900,
    unitCost: 400,
    additionalCosts: [],
    monthlyFixedCost: 60000,
    paymentFeeRate: 3.6,
    discountRate: 0,
    shippingCost: 500,
    salesChannels: ['ec'],
    status: 'draft',
    expectedSalesVolume: 25,
    memo: '発売準備中。ラベルデザイン確認待ち。',
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'prod-005',
    projectId: 'proj-002',
    name: 'リネンブラウス オーバーサイズ',
    code: 'LBL-OS',
    category: 'apparel',
    colors: ['ホワイト', 'ベージュ', 'サックス'],
    sizes: ['S', 'M', 'L'],
    variants: [
      { id: 'v-005-1', color: 'ホワイト', size: 'S', sku: 'LBL-OS-WH-S', stock: 5 },
      { id: 'v-005-2', color: 'ホワイト', size: 'M', sku: 'LBL-OS-WH-M', stock: 8 },
      { id: 'v-005-3', color: 'ベージュ', size: 'M', sku: 'LBL-OS-BE-M', stock: 6 },
      { id: 'v-005-4', color: 'サックス', size: 'L', sku: 'LBL-OS-SK-L', stock: 4 },
    ],
    sellingPrice: 14800,
    wholesalePrice: 7400,
    unitCost: 3200,
    additionalCosts: [],
    monthlyFixedCost: 80000,
    paymentFeeRate: 3.6,
    discountRate: 0,
    shippingCost: 800,
    salesChannels: ['ec', 'made_to_order'],
    status: 'active',
    expectedSalesVolume: 15,
    memo: '春夏コレクションメイン商品。',
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-04-12T10:00:00Z',
  },
  {
    id: 'prod-006',
    projectId: 'proj-002',
    name: 'コットンワイドパンツ',
    code: 'CWP-001',
    category: 'apparel',
    colors: ['ブラック', 'ベージュ'],
    sizes: ['S/M', 'M/L'],
    variants: [
      { id: 'v-006-1', color: 'ブラック', size: 'S/M', sku: 'CWP-BK-SM', stock: 7 },
      { id: 'v-006-2', color: 'ベージュ', size: 'M/L', sku: 'CWP-BE-ML', stock: 5 },
    ],
    sellingPrice: 12800,
    wholesalePrice: 6400,
    unitCost: 2800,
    additionalCosts: [],
    monthlyFixedCost: 80000,
    paymentFeeRate: 3.6,
    discountRate: 0,
    shippingCost: 800,
    salesChannels: ['ec'],
    status: 'inactive',
    expectedSalesVolume: 10,
    memo: '先行予約受付中。入荷待ち。',
    createdAt: '2026-03-10T09:00:00Z',
    updatedAt: '2026-04-08T10:00:00Z',
  },
]

export const SAMPLE_DOCUMENTS: Document[] = [
  {
    id: 'doc-001',
    projectId: 'proj-001',
    type: 'purchase_order',
    title: '発注書 #001',
    issueDate: '2026-04-10',
    dueDate: '2026-04-30',
    recipientName: '株式会社フレグランスジャパン',
    issuerName: 'Lumière Atelier 山田 花子',
    items: [
      {
        productId: 'prod-001',
        productName: 'アロマキャンドル ラベンダー S',
        productCode: 'ARC-LAV-S',
        quantity: 50,
        unitPrice: 480,
        subtotal: 24000,
        memo: '',
      },
      {
        productId: 'prod-003',
        productName: 'リードディフューザー ローズ',
        productCode: 'RDF-ROS',
        quantity: 20,
        unitPrice: 1200,
        subtotal: 24000,
        memo: '200ml版を優先',
      },
    ],
    subtotal: 48000,
    tax: 4800,
    total: 52800,
    memo: '納期厳守でお願いします。',
    createdAt: '2026-04-10T10:00:00Z',
  },
]

// Sample calc result (for display in Home screen)
export const SAMPLE_CALC = {
  productName: 'アロマキャンドル ラベンダー S',
  revenue: 66000,
  grossProfit: 51780,
  grossMargin: 78.5,
  netProfit: 6780,
  breakEvenVolume: 25,
}
